POST http://localhost:8000/open/native/ HTTP/1.1
Content-Type: application/json

{

}

### jsapi 下单
POST http://localhost:8000/open/wechatpay/v3/pay/transactions/jsapi HTTP/1.1
Content-Type: application/json
Accept: application/json, text/plain, */*

{
    "description": "测试商品",
    "out_trade_no": "26a4435196871ff30d20230216124234",
    "notify_url": "https://www.tigerzh.com/api/open/notify",
    "goods_tag": "asdfasf",
    "support_fapiao": false,
    "amount": {
        "total": 1,
        "currency": "CNY"
    },
    "payer": {
		"openid": "ouGWL5htUfPCgH02DDC-q4XaLOb0"
	}
}
### 调起支付
POST https://www.tigerzh.com/api/open/wechatpay/v3/pay/transactions/native HTTP/1.1
Content-Type: application/json
Accept: application/json, text/plain, */*

{
    "description": "测试商品",
    "out_trade_no": "26a4435196871ff30d20230216124233",
    "notify_url": "https://www.tigerzh.com/api/open/notify",
    "goods_tag": "asdfasf",
    "support_fapiao": false,
    "amount": {
        "total": 1,
        "currency": "CNY"
    }
}

### 查询订单
GET http://localhost:8000/open/wechatpay/v3/pay/transactions/id/4200001739202302179611135797?mchid=1637520134 HTTP/1.1
Content-Type: application/json
### 查询投诉单列表API
GET http://localhost:8000/open/wechatpay/v3/merchant-service/complaints-v2?begin_date=2023-02-11&end_date=2023-02-12 HTTP/1.1
Content-Type: application/json
###
POST https://api.weixin.qq.com/cgi-bin/menu/create HTTP/1.1
Content-Type: application/json

{"button": [{"type": "miniprogram", "name": "\u6d4b\u8bd5", "url": "http://mp.weixin.qq.com/", "appid": "wxc06f08cd947ff16a", "pagepath": "/pages/index/index"}]}
### 公众号接口
get http://localhost:8000/open/wechatmp/cgi-bin/get_current_selfmenu_info HTTP/1.1
Content-Type: application/json

{
    "button": [
        {
            "type": "miniprogram", 
            "name": "测试", 
            "url": "http://mp.weixin.qq.com/", 
            "appid": "wxc06f08cd947ff16a", 
            "pagepath": "/pages/index/index"
        }
    ]
}
###
GET http://localhost:8000/open/mpMessage?signature=34d77a55488100b5b932e73400c27ad8c01f3b22&timestamp=1676712988&nonce=148406132&openid=ouGWL5htUfPCgH02DDC-q4XaLOb0 HTTP/1.1


###
GET https://api.mch.weixin.qq.com/v3/pay/transactions/id/4200001739202302179611135797?mchid=1637520134 HTTP/1.1
Content-Type: application/json
Accept: application/json, text/plain, */*,
Authorization: 'WECHATPAY2-SHA256-RSA2048 mchid="1637520134",nonce_str="1C01489D99F1471F9EDAEA043F2E6DCE",signature="aTMiRbllFt6iXZBeYgH0gS4Z+YpUufEyZ7OOgAGcZPHfSBDfXJHoDVVPZjVkYlOr5V20Ejwftysr+q4JQJd/fkZdYqm736cZWSwIjXJk2/cJjVqGumQuK873CIQ9CCyoLnzmuBubIqCdctV64M1/3inybZ96n5n4jYfzuTmGmlOMKdyQINuZsMXyGmwlnkzqutp+yjZVz6+CwRA6q5OaX+4u8mZswHv3B0+w0TfunFfbnkyW9ILSD9WNxrk6OdmgH3ZVrC6eDrlX3WSfMZ/SU9a/OAs+3ZEb+2+TDFfW+bmy2mz1NhJQvryrZLxI8zn9hSVTYNLYBcp/uY7luBbw2A==",timestamp="1676613424",serial_no="317F5F4B9EBCB8869618B17E3F9A0B1B63E90DAE"'
 

###
POST http://localhost:8000/login/ HTTP/1.1
Content-Type: application/json

{
  "captcha": "1",
  "captchaKey":"2",
  "username": "admin",
  "password": "123456" 
}
###
curl 'https://webapi.jutuike.com/user/info' \
  -H 'authority: webapi.jutuike.com' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: zh-CN,zh;q=0.9,en;q=0.8,de;q=0.7' \
  -H 'cache-control: no-cache' \
  -H 'origin: https://pub.jutuike.com' \
  -H 'pragma: no-cache' \
  -H 'sec-ch-ua: "Chromium";v="110", "Not A(Brand";v="24", "Google Chrome";v="110"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36' \
  -H 'xx-token: B0570sJslG2eVkw7qTyWWk5bC99mIwdR' \
  --compressed